#!/usr/bin/env python3
"""Regenerate docs/third-party-licenses.md from the modules compiled into ./cmd/...

Fails (exit 1) if any module has no recognisable licence or is copyleft
(GPL/LGPL/AGPL/MPL), so a dependency that would conflict with Apache-2.0
cannot slip in unnoticed. Usage: make licenses
"""
import glob, os, re, subprocess, sys
from collections import Counter

def classify(text):
    t = text.lower()
    if 'gnu affero' in t: return 'AGPL'
    if 'gnu lesser general' in t: return 'LGPL'
    if 'gnu general public license' in t: return 'GPL'
    if 'mozilla public license' in t: return 'MPL-2.0'
    if 'apache license' in t and 'version 2.0' in t: return 'Apache-2.0'
    if 'permission is hereby granted, free of charge' in t: return 'MIT'
    if 'redistribution and use in source and binary forms' in t:
        return 'BSD-3-Clause' if ('neither the name' in t or 'endorse or promote' in t) else 'BSD-2-Clause'
    if 'permission to use, copy, modify, and/or distribute' in t: return 'ISC'
    return 'UNKNOWN'

out = subprocess.run(
    ['go', 'list', '-deps', '-f', '{{with .Module}}{{if not .Main}}{{.Path}}|{{.Version}}|{{.Dir}}{{end}}{{end}}', './cmd/...'],
    check=True, capture_output=True, text=True).stdout
rows, bad = [], []
for line in sorted(set(filter(None, out.splitlines()))):
    path, ver, d = line.split('|')
    kinds = set()
    for f in glob.glob(os.path.join(d, '*')):
        if os.path.isfile(f) and re.search(r'(licen[sc]e|copying)', os.path.basename(f), re.I):
            kinds.add(classify(open(f, errors='ignore').read()))
    if len(kinds) > 1: kinds.discard('UNKNOWN')
    lic = '/'.join(sorted(kinds)) or 'UNKNOWN'
    if lic == 'UNKNOWN' or re.search(r'GPL|MPL', lic): bad.append((path, ver, lic))
    rows.append((path, ver, lic))

with open('docs/third-party-licenses.md', 'w') as f:
    f.write('# Third-party licences\n\nGenerated by `make licenses` from the Go modules compiled into the binaries in `cmd/`.\n'
            'Do not edit by hand. Our own code is Apache-2.0 (see [LICENSE](../LICENSE)); every licence below is\n'
            'permissive and compatible with it. The vendored remotedialer fork is described in [NOTICE](../NOTICE).\n\n')
    f.write('| Module | Version | Licence |\n|---|---|---|\n')
    for p, v, l in rows: f.write(f'| `{p}` | {v} | {l} |\n')
    f.write('\nSummary: ' + ', '.join(f'{k} {n}' for k, n in sorted(Counter(r[2] for r in rows).items())) + '\n')
print(f'{len(rows)} modules;', dict(Counter(r[2] for r in rows)))
if bad:
    print('PROBLEM: needs review:', bad, file=sys.stderr); sys.exit(1)
