apiVersion: v1
kind: Service
metadata:
  name: {{ include "sextant.fullname" . }}
  labels: {{- include "sextant.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector: {{- include "sextant.selectorLabels" . | nindent 4 }}
  ports:
    - name: https
      port: {{ .Values.service.port }}
      targetPort: https
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
